### ISSUE TITLE
AMD Loading

### ISSUE THREAD

**Issue by Joeao** [reedsy/quill-cursors#1]
Hey there,

Trying out your project to see if I can implement basic quill cursors on selection-change and text-change. I'm loading modules with RequireJS but am having difficulty with quill-cursors. I've listed Quill as a dependency for quill-cursors, however quill-cursors seems to be looking for Quill before instantiation of a Quill instance, which causes the following error.

```javascript
quill-cursors.js:1804 Uncaught ReferenceError: Quill is not defined
    at Object.<anonymous> (quill-cursors.js:1804)
    at __webpack_require__ (quill-cursors.js:20)
    at Object.rangeFix (quill-cursors.js:75)
    at __webpack_require__ (quill-cursors.js:20)
    at Object.<anonymous> (quill-cursors.js:1817)
    at __webpack_require__ (quill-cursors.js:20)
    at Object.defineProperty.value (quill-cursors.js:66)
    at quill-cursors.js:69
```

My reasons for migrating to Webpack are piling up, so if this isn't something you intend to address, maybe I should start the process of making a move.

Thanks for the great work

**Comment by pedrosanta** [comment]
Hi @Joeao, thanks.

Yep, I haven't tested it with RequireJS but I'm also not entirely happy with the packaging of the module.

I'll try it with RequireJS to check, and if you can put up a minimal working example of it with RequireJS on a repository and share, feel free.

Also, as a note, I'm working to put up a complete scenario with server and client handling cursors synchronization at [pedrosanta/quill-sharedb-cursors](https://github.com/pedrosanta/quill-sharedb-cursors), feel free to check out. 😊 (Let's get these dreaded cursors workin'!)

As I said, will experiment with RequireJS and get back. Cheers.

**Comment by Joeao** [comment]
Hey @pedrosanta, I'm actually in the process of moving from RequireJS to Webpack and from my own templating engine to Marko. So this issue isn't actually a priority for me personally, however maybe it's something you want to address for others some time in the future so I'll set up a RequireJS project tomorrow, for the cause.

I'm using [YJS](https://github.com/y-js) as an alternative to sharedb, it's pretty cool and worth checking out if you've not heard of it before. The developer [is waiting](https://gitter.im/y-js/yjs?at=5900517bc1d3b501541fd0a1) on a Quill implementation of multi-cursor and will work it into YJS when ready. I'll let him know about this project once I've tried it out.

**Comment by Joeao** [comment]
Here's a [repo](https://github.com/Joeao/quill-cursor-requirejs) to reproduce the error. Kept it minimal for the sake of simplicity. If you have any questions stick them here or on the repo issues, it's not serving any other purpose.
Cheers guy

**Comment by pedrosanta** [comment]
Boom! Thanks for the repo @Joeao.

So, I've cloned it and tested it with the lib, and made a few changes, namely **publishing the lib/module as UMD**.

So I've released a new version that should work with RequireJS, but... you need to update a few things on your example namely:
* Since Quill library is exposed as `Quill` ([you can check out its Webpack config](https://github.com/quilljs/quill/blob/develop/_develop/webpack.config.js#L46)) and since I'm also requiring that lib/module by that name on Webpack, since you import it as `quill` on RequireJS, it only knows a `quill` lib and doesn't know any `Quill`. So, **you must import that module exactly as `Quill`**:

```
requirejs.config({
    baseUrl: '/',
    paths: {
        "domReady": "../libs/domReady",
	"Quill": "./libs/quill",
        "QuillCursors": "./libs/quill-cursors/quill-cursors"
    },
    shim: {
        "QuillCursors": {
            deps: ['Quill'],
            exports: 'QuillCursors'
        }
    }
});

require(
    [
        "Init"
    ]
);
```

* And so on init you'll need to update as well:

```
/**
 * Init.js
 */

define(
    "Init",

    [
    	"domReady",
        "Quill",
        "QuillCursors"
    ],

    function(domReady, Quill, QuillCursors) {
    	domReady(function() {       
            console.log('Initialising Quill instance');

            var quill = new Quill('#editor', {
                theme: 'snow',
                modules: {
                    cursors: true
                }
            });
    	});
    }
);
```

I think this might do the trick! 😉 Thanks for spotting this and for the help @Joeao.

**Comment by pedrosanta** [comment]
Also, @Joeao, as a note and as I said, I've finished adding the relevant documentation on the current cursors efforts/discussion regarding Quill at [pedrosanta/quill-sharedb-cursors](https://github.com/pedrosanta/quill-sharedb-cursors).

I've added [some notes regarding Ysj as well](https://github.com/pedrosanta/quill-sharedb-cursors#other-backends-meteor-yjs).

Cheers!

**Comment by pedrosanta** [comment]
Ok, nevermind what I said @Joeao, [I've updated webpack configuration](https://github.com/reedsy/quill-cursors/commit/486469b5556a2102ffdbaac8828b64e11a09616d), because `external` config for Quill should have different 'names' depending on the module packaging/global var.

It should be working properly with your code now. Can you confirm and close the issue?
