### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by NULLx76** [reedsy/quill-cursors#22]
It would be great if the types were also generated upon build and added to the dist so that when using the plugin with TS people can make use of the typings

**Comment by alecgibson** [comment]
I've had a very quick look at this, but getting the TypeScript definitions to play nicely with Webpack appears to be non-trivial. I've tried the following with no success:

  - [`declaration-bundler-webpack-plugin`][1], which doesn't build properly. I tried with [this fix][2], which generates a declaration, but it doesn't appear to be valid
  - [this StackOverflow answer][3] which potentially gets a little closer, but still doesn't work
  - [`dts-bundle-webpack`][4] which is a neater version of the above StackOverflow solution

I _think_ this isn't working because we use `default` exports, which don't work very well when being combined into a single `d.ts` file. We could potentially move away from that, but it would be a breaking change, so I'd be inclined to leave it for if we want to make more big changes.

I probably don't have a lot of time to look into this, as it's a nice-to-have. Please feel free to raise a PR if you think you can crack it, though.

[1]: https://www.npmjs.com/package/declaration-bundler-webpack-plugin
[2]: https://github.com/TypeStrong/ts-loader/issues/263#issuecomment-425692743
[3]: https://stackoverflow.com/a/43041131/4003671
[4]: https://www.npmjs.com/package/dts-bundle-webpack

**Comment by RobbinBaauw** [comment]
A trivial but ugly solution (until it is possible to move away from default exports) would be making a definition file by hand. As there are not that many methods this should be very easy and quick. Thoughts on that?

**Comment by alecgibson** [comment]
Making one by hand is a bit icky in my opinion. I think I'd rather remove our `default` exports. I guess it's arguable that it's not a breaking change, because consumers shouldn't really have been trying to use anything other than the single point of entry into the module, and so long a that stays consistent, then it's fine. Or we just bump to v3 anyway. I guess it doesn't matter too much.

**Comment by pedrosanta** [comment]
> Or we just bump to v3 anyway. I guess it doesn't matter too much.

Yeap. If it can be breaking better to bump, IMO.

**Comment by alecgibson** [comment]
Should now hopefully be fixed by https://github.com/reedsy/quill-cursors/pull/54

Release coming soon.

**Comment by vlazh** [comment]
@alecgibson, can't wait for this!
