### ISSUE TITLE
Cursor range does not adjust when entering text

### ISSUE THREAD

**Issue by himynameistimli** [reedsy/quill-cursors#25]
### Use Case:
I'm trying to use this with websockets for online collaboration (typical use case). I have a server that just relays messages to and from the client browser.

### Problem:
If person A selects a range, person B will see the range selected on their editor. If person B edits that document, while person A does nothing, the cursor range does not exhibit expected behavior.

I have two situations that occur right now.

1) I can relay that information back and forth to get the updated selection. In other words:
	- A selects range
	- B starts typing
	- A sees the changes on their editor via websockets
	- A's editor then relays the updated selected range back thru the websocket
	- B receives the updated range and moves the cursor.

However I get this situation (and it would be worse on a server that is further away).

![Kapture 2019-03-28 at 18 45 04](https://user-images.githubusercontent.com/6541272/55151979-61396980-518a-11e9-880a-9329e6c3b46b.gif)

2) Or if I don't forward the updated range, I get this issue:

![Kapture 2019-03-28 at 18 43 37](https://user-images.githubusercontent.com/6541272/55152025-7a421a80-518a-11e9-9e8d-63a28bab2c0d.gif)

I'm not sure if its an bug or a misconfiguration on my end, but my expected behavior is that the cursor's range would get updated automatically.

The demo is different because I think when the editor loses focus, the range disappears altogether.

**Comment by alecgibson** [comment]
Yeah, this is due to a simplification we made when refactoring. It's on my radar to put back the old behaviour. I can try to have a look today perhaps.

**Comment by alecgibson** [comment]
@himynameistimli I've had a quick stab at trying to fix this issue. Could you please try this version of `quill-cursors` and let me know how you get on?

[quill-cursors.js.zip](https://github.com/reedsy/quill-cursors/files/3022205/quill-cursors.js.zip)

Note that you'll need to tweak how you use `quill-cursors`:

  - when instantiating, set the option `tranformOnTextChange: true`
  - you'll probably want to debounce cursor updates to avoid laggy performance

For more details, see the [updated example][1].

[1]: example/main.js

**Comment by houshuang** [comment]
Curious about this - are you guys not using ShareDB for the syncing, but something simpler? It's strange to me that the quill-cursors repo seems to get so much love (awesome!), but I don't see any public modules for connecting this with ShareDB or other mechanisms? 

We've been connecting this to ShareDB, by using the @teamwork/sharedb fork's presence functionality, and extending this to ot-rich-text for Quill deltas. We're planning to share these - let me know if anyone else is working on this so we can collaborate.

My confusion is that in the presence code, there is a "transformCursor" which is automatically called on the client-side whenever there is a local or remote text-change event. It seems to me (after some experimentation) that this makes the transformTextOnChange setting not just superfluous, but harmful (if I used the setting, it looked really janky, without it, it looked great - although I need to do more testing with high latency). 

Perhaps this is just as expected, and this additional setting is intended for people who use simpler mechanisms for editing (but then, how do you avoid editing conflicts?)... I was just automatically assuming people would be using this with ShareDB.

**Comment by pedrosanta** [comment]
Hi @houshuang, thanks for the kind words and support.

Say, I've got a simple example working over at [pedrosanta/quill-sharedb-cursors](https://github.com/pedrosanta/quill-sharedb-cursors).It's a bit outdated at the moment though, but perhaps can be helpful to you by inspecting the code, etc.

Just sharing the reference.

Cheers! 🙌

**Comment by houshuang** [comment]
Hi @pedrosanta, thanks for the quick reply. I certainly did look at that repo, it was a major inspiration, but I did find the implementation have a lot of quirks, because of storing presence separately. I believe this works much better with the presence module from teamwork. 

@alecgibson Interesting, could you explain more about the debounce? So basically bundling ops locally before shipping them off? Any reason for this? We've just let ShareDB "do it's thing", and it's been working well for us. 

The way I've been doing it is this: 
- extending the work by teamwork to add presence to ot-rich-text (Quill deltas), and also ot-json0 (for now very simple, it simply forwards to the subtype, haven't implemented for other types yet, but will add text0 very soon). 
- I borrowed your idea of debouncing the presence announcements, so when you are typing rapidly, it only emits text change ops, and it runs the ot-rich-text transformCursor function on the client, both in the client typing, and the clients receiving text-ops, to update all selections/cursors. The manual presence update is really only needed when joining/leaving, or manually changing position/selection without making a text change. 

As I said, so far seems to be working very well (finally). Needs a lot of code clean-up, some more generalization of the ot-json0 code etc. I plan to post it soon, would love to have more eyes on this. We plan to depend on this very heavily, so it would be great to get to something very solid.

**Comment by alecgibson** [comment]
Glad to hear it's working! It's hard to cover all use cases, but that's probably why you may not need some features.

At the moment we're debouncing ShareDB op submission using the (very obscure) [`doc.pause()`][1] method. The main reason for this was to try to keep the number of ops in a document low for storage reasons, and to make it easier to jump back to an arbitrary version of a document.

We've since [fixed the versioning issue][2], and our use case is now demanding smoother user updates over storage optimisation, so we'll probably do away with the debounce very soon.

[1]: https://github.com/share/sharedb/blob/d130700771f0877334f9f7be061c0605e7e54bf7/lib/client/doc.js#L821-L824
[2]: https://github.com/share/sharedb/pull/236

**Comment by houshuang** [comment]
Little demo of shared cursors using presence. Will post code very soon. I just cleaned up a bunch of my code, might have left some edge-cases etc. http://116.203.153.109:8080/

**Comment by pedrosanta** [comment]
@houshuang I didn't notice Teamwork PR implemented the ephemeral data concept, cool! Yes, definitely the one socket/channel solution is where we need to be for this, IMO.
