### ISSUE TITLE
Quill-cursors has a memory leak due to missed cleanup for global listeners

### ISSUE THREAD

**Issue by artaommahe** [reedsy/quill-cursors#61]
Adding quill-cursors to our project i found a memory (nodes) leak. Debugging leads me to these lines https://github.com/reedsy/quill-cursors/blob/master/src/quill-cursors/quill-cursors.ts#L102 that setup two global listeners that are never cleared. Manually commenting out this method code in dist js file fixed memory leak. These listeners without cleanup holds quill's dom nodes references in memory and so for each quill instance during page's lifetime.
Quill-cursors should somehow clear this listeners on quill removing.

**Comment by alecgibson** [comment]
These listeners aren't global — they're attached to the Quill container element. I'd expect them to be destroyed when Quill is. Can you provide an example where they're leaking?

**Comment by artaommahe** [comment]
sry, y're right they are not global. Here's a reproduction with angular https://stackblitz.com/edit/angular-quill-cursors?file=src/app/editor.componen.ts

performance memory graph
![image](https://user-images.githubusercontent.com/1944061/119680275-b300db80-be49-11eb-919b-3da632d59529.png)

**Comment by artaommahe** [comment]
here is plain js example  https://stackblitz.com/edit/js-quill-cursors-memory-leak?file=index.js

![image](https://user-images.githubusercontent.com/1944061/119681213-88fbe900-be4a-11eb-8643-b01f715ceeda.png)

**Comment by alecgibson** [comment]
Okay so this looks like it's specifically to do with the `ResizeObserver` (rather than the scroll event listener), which is presumably because the `ResizeObserver` sticks around even after the `Node` is disconnected, and keeps the whole module (and presumably then the whole `Quill` instance?) in memory.

Not entirely sure what to do with this — I was under the impression that `ResizeObservers` should garbage-collect themselves when their nodes are GC'd.

I can get the listener count back down like this:

```ts
    const resizeObserver = new ResizeObserver(([entry]: ResizeObserverEntry[]) => {
      if (!entry.target.isConnected) resizeObserver.disconnect();
      this.update();
    });
```

**However** this approach means that if a consumer disconnects their Quill node, and then reattaches it (not impossible), then the `ResizeObserver` is incorrectly disconnected, and will no longer observe.

**Comment by artaommahe** [comment]
mb at least add destroy() method to manually call resizeObserver disconnecting via `editor.getModule('cursors').destroy()`?
